batch_size: 256
checkpoints_path: ./checkpoints/ablation
dataset: ml2hp
dataset_path: ../../datasets/ml2hp
device: auto
image_backbone_name: null
landmarks_backbone_name: unprocessed
lr: 5.0e-05
max_epochs: 3
merging_method: concatenate
seed: 42
use_horizontal_image: false
use_horizontal_landmarks: true
use_vertical_image: false
use_vertical_landmarks: true
validation: loso
