batch_size: 128
checkpoints_path: ./checkpoints/ablation
dataset: ml2hp
dataset_path: ../../datasets/ml2hp
device: auto
image_backbone_name: dinov2-s
landmarks_backbone_name: linear
lr: 1.0e-05
max_epochs: 3
name: ml2hp_loso_dinov2-s_linear
normalize_landmarks: true
seed: 42
use_horizontal_image: true
use_horizontal_landmarks: true
use_vertical_image: true
use_vertical_landmarks: true
validation: loso
