accumulate_grad_batches: 1
batch_size: 64
checkpoints_path: ./checkpoints/ablation
dataset: ml2hp
dataset_path: ../../datasets/ml2hp
device: auto
image_backbone_name: null
landmarks_backbone_name: linear
lr: 1.0e-05
max_epochs: 3
name: ml2hp_loso_None_linear
normalize_landmarks: true
seed: 42
use_horizontal_image: false
use_horizontal_landmarks: true
use_vertical_image: false
use_vertical_landmarks: true
validation: loso
