accumulate_grad_batches: 1
batch_size: 128
checkpoints_path: ./checkpoints/ablation
dataset: ml2hp
dataset_path: ../../datasets/ml2hp
device: auto
image_backbone_name: clip-b
landmarks_backbone_name: null
lr: 5.0e-05
max_epochs: 3
name: ml2hp_loso_clip-b_None
normalize_landmarks: true
seed: 42
use_horizontal_image: true
use_horizontal_landmarks: false
use_vertical_image: true
use_vertical_landmarks: false
validation: loso
