batch_size: 256
checkpoints_path: ./checkpoints/ablation
dataset: ml2hp
dataset_path: ../../datasets/ml2hp
device: auto
image_backbone_name: convnextv2-t
landmarks_backbone_name: mlp
lr: 0.0001
max_epochs: 1
name: ml2hp_loso_convnextv2-t_mlp
normalize_landmarks: true
seed: 42
use_horizontal_image: true
use_horizontal_landmarks: true
use_vertical_image: true
use_vertical_landmarks: true
validation: loso
